graph LR

%% ...::: NODES :::...

input[Image]
cnn(CNN)
feature_map[Feature Map]
rpn(Region Proposals)
roi(RoI Pooling)

clas(Class)
bounding_box(Bounding Box)

%% ...::: STYLING :::...

%% style input fill:#bddaff,stroke:#4294ff
style rpn fill:#f9f

%% ...::: FLOWS :::...

input-->cnn
cnn-->feature_map
feature_map-->rpn

feature_map-.->roi
rpn-->roi
subgraph for a given region proposal
  roi-->clas
  roi-->bounding_box
end
