graph LR

%% ...::: NODES :::...

input((Obraz))
cnn(CNN)
feature_map[Mapa Cech]
rpn(Regiony)
roi(RoI Pooling)

clas(Klasa)
bounding_box(Obwiednia)
mask(Maska)

%% ...::: STYLING :::...

%% style input fill:#bddaff,stroke:#4294ff
style mask fill:#f9f

%% ...::: FLOWS :::...

input-->cnn
cnn-->feature_map
feature_map-->rpn

feature_map-.->roi
rpn-->roi
subgraph dla danego regionu
  roi-->clas
  roi-->bounding_box
  roi-->mask
end
