graph LR

%% ...::: NODES :::...

input[/Obraz\]
region_proposals(Regiony)
cnn(CNN)
svm_classification(Klasa)
bounding_box_improvement(Obwiednia)

%% ...::: STYLING :::...

%% style input fill:#bddaff,stroke:#4294ff

%% ...::: FLOWS :::...

input-->region_proposals
region_proposals-->cnn
subgraph dla danego regionu
  cnn-->svm_classification
  svm_classification-->bounding_box_improvement
end
