version: 2

jobs:
  compile-thesis:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: thesis/compile.sh

workflows:
  badminton-monorepo:
    jobs:
      - compile-thesis
