version: 2.1

orbs:
  badminton-monorepo:
    commands:
      install-git-lfs:
        steps:
          - run:
              name: Install git lfs
              command: |
                curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
                sudo apt-get install git-lfs -y
      checkout-with-lfs:
          steps:
            - checkout
            - install-git-lfs
            - run: git submodule init && git submodule update
            - run: git lfs install
            - run: git lfs pull
            
jobs:
  build-js:
    docker:
      - image: circleci/node:10.15
    steps:
        - checkout
        - run: yarn install
        - run: yarn workspace frontend run build-dist
  compile-thesis:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: cd thesis && ./compile.sh
  run-train:
    docker:
      - image: eu.gcr.io/badminton/badminton_image
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - run: cd badminton && ./train.sh
  run-detection:
    docker:
      - image: circleci/node:10.15
    steps:
      - badminton-monorepo/checkout-with-lfs
      - run: ls -al
workflows:
  version: 2
  badminton-monorepo:
    jobs:
      - run-detection
