version: 2.1

commands:
  checkout-with-submodules:
      steps:
        - checkout
        - run:
            name: Initialize submodules
            command: git submodule init && git submodule update
        - run:
            name: Install system dependencies
            command: sudo apt-get update && sudo apt-get install -yq realpath
        - run:
            name: Initialize git lfs
            command: |
              curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
              sudo apt-get install git-lfs -yq
              git lfs install
              git lfs pull

executors:
  docker-node:
    docker:
      - image: circleci/node:10.15
  machine-classic:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: false

jobs:
  build-js:
    executor: docker-node
    steps:
        - checkout
        - run: yarn install
        - run: yarn workspace frontend run build-dist
  compile-thesis:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run:
          name: Install node and npm dependencies
          command: |
            apt-get update && apt-get install nodejs npm -yq
            cd thesis && npm install
      - run: 
          name: Install chrome dependencies
          command: |
            apt-get update &&
            apt-get install -yq --no-install-recommends libnss3 \
            libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
            libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
            libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
      - run: thesis/scripts/all.sh
      - run:
          name: Assert artifact exists
          command: test -f thesis/main.pdf
      - store_artifacts:
          path: thesis/main.pdf
          destination: main.pdf
  run-nn:
    executor: machine-classic
    steps:
      - checkout-with-submodules
      - run:
          name: Run training
          command: cd badminton/docker && ./train.sh
      - run:
          name: Assert artifact exists
          command: test -f badminton/training/result.h5
      - run:
          name: Assert that test results exist
          command: |
            cd badminton/training/logs
            [ $(ls * | grep .jpg | wc -l) -gt 0 ]
      - run:
          name: Run detection
          command: |
            mv badminton/training/result.h5 badminton/detection/weights.h5
            cd badminton/docker && ./detect.sh
      - run:
          name: Assert artifact exists
          command: cd badminton/detection && ( test -f ./output.jpg || test -f ./output.png )
  run-detection:
    executor: machine-classic
    steps:
      - checkout-with-submodules
      - attach_workspace:
          at: badminton/detection/workspace
      
workflows:
  version: 2
  badminton-monorepo:
    jobs:
      - build-js:
          filters:
            branches:
              only: 
                - master
                - /js-.*/
                - /ci-.*/
      - compile-thesis:
          filters:
            branches:
              only: 
                - master
                - /thesis-.*/
                - /ci-.*/
      - run-nn:
          filters:
            branches:
              only: 
                - master
                - /nn-.*/
                - /ci-.*/
