version: 2

jobs:
  build-js:
    docker:
      - image: circleci/node:10.15
    steps:
        - checkout
        - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
              - node_modules-{{ .Branch }}-
              - node_modules-
        - run: yarn install
        - save_cache:
              paths:
                - ./node_modules
              key: node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
  compile-thesis:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: cd thesis && ./compile.sh
workflows:
  version: 2
  thesis:
    jobs:
      - compile-thesis
  javascript:
    jobs:
      - build-js
