version: 2.1

orbs:
  badminton-monorepo:
    commands:
      checkout-with-lfs:
          steps:
            - checkout
            - run:
                name: Initialize submodules
                command: git submodule init && git submodule update
            - run:
                name: Initialize git lfs
                command: |
                  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
                  sudo apt-get install git-lfs realpath -y
                  git lfs install
                  git lfs pull
    executors:
      docker-node:
        docker:
          - image: circleci/node:10.15
      machine-with-docker-caching:
        machine:
          image: circleci/classic:latest
          docker_layer_caching: true
jobs:
  build-js:
    executor: badminton-monorepo/docker-node
    steps:
        - checkout
        - run: yarn install
        - run: yarn workspace frontend run build-dist
  compile-thesis:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: cd thesis && ./compile.sh
  run-train:
    docker:
      - image: eu.gcr.io/badminton/badminton_image
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - run: cd badminton && ./train.sh
  run-detection:
    executor: badminton-monorepo/machine-with-docker-caching
    steps:
      - badminton-monorepo/checkout-with-lfs
      - run: cd badminton/docker && ./detect.sh
workflows:
  version: 2
  badminton-monorepo:
    jobs:
      # - run-detection
      - compile-thesis
