version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
        - checkout
        - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
              - node-v1-{{ .Branch }}-
              - node-v1-
        - save_cache:
            paths:
              - ./node_modules
            key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - run: yarn install
  compile-thesis:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: cd thesis && ./compile.sh
workflows:
  version: 2
  thesis:
    jobs:
      - build
      - compile-thesis
  javascript:
    jobs:
      - build
