version: 2
jobs:
  build-js:
    docker:
      - image: circleci/node:10.15
    steps:
        - checkout
        - run: yarn install
        - run: yarn workspace frontend run build-dist
  compile-thesis:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: cd thesis && ./compile.sh
  run-train:
    docker:
      - image: eu.gcr.io/badminton/badminton_image
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - run: cd badminton && ./train.sh
  run-detection:
    docker:
      - image: eu.gcr.io/badminton/badminton_image
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - run: cd badminton/detection && python3 ./detect.py
workflows:
  version: 2
  badminton-monorepo:
    jobs:
      - run-detection
