version: 2.1

orbs:
  badminton-monorepo:
    commands:
      checkout-with-lfs:
          steps:
            - checkout
            - run:
                name: Initialize submodules
                command: git submodule init && git submodule update
            - run:
                name: Initialize git lfs
                command: |
                  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
                  sudo apt-get install git-lfs -y
                  git lfs install
                  git lfs pull
            
jobs:
  build-js:
    docker:
      - image: circleci/node:10.15
    steps:
        - checkout
        - run: yarn install
        - run: yarn workspace frontend run build-dist
  compile-thesis:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: cd thesis && ./compile.sh
  run-train:
    docker:
      - image: eu.gcr.io/badminton/badminton_image
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - run: cd badminton && ./train.sh
  run-detection:
    docker:
      - image: circleci/node:10.15
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - badminton-monorepo/checkout-with-lfs
      - run: cd badminton/docker && ./detect.sh
workflows:
  version: 2
  badminton-monorepo:
    jobs:
      - run-detection
