graph TD

%% ...::: NODES :::...

input[Obraz wejściowy]
blur(Rozmazanie)
edges(Filtr Canny)
hough(Transformacja Hough)
group(Grupowanie i odfiltrowanie linii)
line_extend(Wydłużenie linii środkowych)
remove_degraded(Usunięcie zdegradowanych odcinków)
shorten(Skrócenie par linii do skrajnych przecięć)
podzial(Podział na linie poziomie i pionowe)
verif(Weryfikacja)
court[Zdetektowany obszar kortu]

%% ...::: STYLING :::...

%% ...::: FLOWS :::...

input-->blur
blur-->edges
edges-->hough
hough-->group
group-->line_extend
line_extend-->remove_degraded
remove_degraded-->shorten
shorten-->podzial
podzial-->verif
verif-->court
